toji/gl-matrix

- src/gl-matrix/mat4.js
- src/gl-matrix/quat.js
- src/gl-matrix/vec3.js
I am not sure how useful the interpolation functions are for other people.
mat4.fromRotationTranslationScale sure is useful, at least for me.
> Some new functions

- spec/gl-matrix/mat2-spec.js
- spec/gl-matrix/mat2d-spec.js
- spec/gl-matrix/mat3-spec.js
- spec/gl-matrix/mat4-spec.js
- src/gl-matrix/mat2.js
- src/gl-matrix/mat2d.js
- src/gl-matrix/mat3.js
- src/gl-matrix/mat4.js
I only needed this for mat3 but added it for the rest for consistency. It's certainly not as commonly needed as matrix multiplication, but it comes up frequently in physics problems.
I only did a scalar implementation for mat4, largely since SIMD is not well supported at all and so it's not something that is worth doing for me.
I'd also like to add matrix equivalents to `vec{N}.addAndScale`, (e.g. taking a scalar and another matrix, and working equivalently to `A = A + B*c` where A and B are matrices, and c is a scalar), since this is another operation I find myself doing. I didn't do this because I felt it would cause confusion with `mat{N}.scale` (for that matter, I'd also like to add multiplication of a matrix by a scalar...). If you can come up with better names for those, I'd be …
> Implement add/subtract for mat2, mat2d, mat3, and mat4

- spec/gl-matrix/mat4-spec.js
Fixes to incomplete matrices in tests introduced by my recent patches. 
Not sure how some of them didn't cause a test failure (the one where I left off half of the matrix seems like it should have failed).
> Fix broken mat4.subtract, mat4.set, and mat4.fromValues tests

- spec/gl-matrix/mat2-spec.js
- spec/gl-matrix/mat2d-spec.js
- spec/gl-matrix/mat3-spec.js
- spec/gl-matrix/mat4-spec.js
- src/gl-matrix/mat2.js
- src/gl-matrix/mat2d.js
- src/gl-matrix/mat3.js
- src/gl-matrix/mat4.js
Basically the matrix versions of `vec{N}.scale` and `vec{N}.scaleAndAdd` respectively. The name difference is due to the fact that `mat{N}.scale` is already taken.
> Add multiplyScalar and multiplyScalarAndAdd functions for matrices

- spec/gl-matrix/common-spec.js
- spec/gl-matrix/mat2-spec.js
- spec/gl-matrix/mat2d-spec.js
- spec/gl-matrix/mat3-spec.js
- spec/gl-matrix/mat4-spec.js
- spec/gl-matrix/quat-spec.js
- spec/gl-matrix/vec2-spec.js
- spec/gl-matrix/vec3-spec.js
- spec/gl-matrix/vec4-spec.js
- src/gl-matrix/common.js
- src/gl-matrix/mat2.js
- src/gl-matrix/mat2d.js
- src/gl-matrix/mat3.js
- src/gl-matrix/mat4.js
- src/gl-matrix/quat.js
- src/gl-matrix/vec2.js
- src/gl-matrix/vec3.js
- src/gl-matrix/vec4.js
Strict equality comparison, e.g. ===. So this might do the wrong thing for NaNs, depending on your perspective.  
I considered adding a matching approxEquals as well, but considering that I didn't need it, and that the way to do accurately has some overhead that a lot of people might find undesirable (the obvious `Math.abs(x-y) < epsilon` fails for large x and y, so you need to do  `Math.abs(x-y) < epsilon*Math.max(1.0, Math.abs(x), Math.abs(y))`)... I punted on it.
> Implement equals function for all types

- bower.json
Hey, great library.
It would be nice if you would include the src folder in the bower package, that way I can load (and bundle) the modules I need directly in my application.
> Include src folder in bower package

- spec/gl-matrix/mat4-spec.js
- spec/gl-matrix/quat-spec.js
- src/gl-matrix/mat4.js
- src/gl-matrix/quat.js
**OVERVIEW**
I added methods for extracting useful information from mat4 and quat objects. This addresses issue https://github.com/toji/gl-matrix/issues/136 (which is also an issue I faced using gl-matrix in my own work).
For mat4, I added a mat4.getTranslation and mat4.getRotation method. They return the vec3 translation and quat rotation stored in a transformation matrix, respectively.
For quat, I added a quat.getAxisAngle method. This returns the unit vector axis and angle (radians) rotation stored by the input quaternion.
**MATHEMATICAL CONSIDERATIONS**
A single axis/angle rotation may be stored by at least two different quaternions. If an axis of rotation is [a, b, c] and the angle of rotation d, the same rotation may be described by an axis of rotation [-a, -b, -c] and an angle 2*PI …
> Add decomposition methods to mat4 and quat

- spec/gl-matrix/vec2-spec.js
- spec/gl-matrix/vec3-spec.js
- spec/gl-matrix/vec4-spec.js
- src/gl-matrix/vec2.js
- src/gl-matrix/vec3.js
- src/gl-matrix/vec4.js
I've been monkey-patching these into `gl-matrix` for years; it's time they're merged in.
They're particularly useful when working with 2D grids, 3D lattices and bounding volumes.
The vec4 variants are useful for ray-casting in 4D; where a surface exists only for an interval in time. 
I've attempted to logically sequence the methods within the appropriate files.
I've also provided tests utilising constants from the `Math` object.
Let me know if you require any adjustments before merging.
> Implement vec{2,3,4}.{ceil,floor,round}

- src/gl-matrix/mat4.js
To support old browsers. (However, I do not know what is the intended support.)
> Remove extra comma in mat4.js

- src/gl-matrix/common.js
Fix for missing typed array support in old browsers.
> Prevent Float32Array undefined error on missing typed array support.

- spec/gl-matrix/mat4-spec.js
- src/gl-matrix/mat4.js
The decompose methods seem to forget a getScaling implementation for mat4
> add getScaling function for mat4

- src/gl-matrix/vec3.js
Example:
var vec1 = [0.024432172998785973, 1.3685636623961273e-8, 0.9997014999389648]
var vec2 = [-0.024432172998785973, -8.114220406696404e-9, -0.9997014999389648]
dot(vec1, vec2) will be -1.0000000200576589
=> For values smaller than -1, the `Math.acos`function returns `NaN` (at least in my Chromium browser), therefore the additional check ensures that the cosine value from the dot product is clamped (as it was already done for values greater 1)
> fixed precision issues in vec3 angle function

- src/gl-matrix/common.js
'this' is undefined in top-level JS modules, `str in this` throws.
> Replace use of 'this'

- spec/helpers/spec-helper.js
in regards to #260 
This wraps the spec-helper.js expect functions in assert calls. This is kind of a clunky fix. An ideal solution would be to migrate to a mocha compatible assertion library. An intermediary solution would be to replace the current expects return values with asserts. I may try that next.
Some of the tests are now failing. This may be a issue with this PR yet or the test may actual failing test cases because the tests were throwing false positives for so long. Will investigate further
> fix test runner

- .npmignore
Closes #284
This PR simply ignores `.babelrc` for NPM released package, avoiding redundant babel transpiling on user's bundle process.
See also https://github.com/ianstormtaylor/slate/pull/1020
> Ignore .babelrc for NPM release

- package.json
instead to put it into `dependencies` @stefnotch 
I'm upgrading Node to v10 and NPM to v6 yesterday but I found that this module installs a local out-dated npm in my `node_modules` directory which does not compatible with Node v10.
I do not understand why we need to install an npm module localy, but I believe that move it to `devDependeicnes` will solve my problem(and potential others')
> Should move `npm` to devDependencies

- package.json
Fixes #300.
I'm wondering though if it's needed to be listed as a dependency at all? I did a repo wide search and it seems the only dependency on NPM is being able to do `npm run`?
> Move NPM to `peerDependencies`.

- src/gl-matrix/mat2.js
- src/gl-matrix/mat2d.js
- src/gl-matrix/mat3.js
- src/gl-matrix/mat4.js
- src/gl-matrix/quat.js
- src/gl-matrix/quat2.js
- src/gl-matrix/vec2.js
- src/gl-matrix/vec3.js
- src/gl-matrix/vec4.js
Since Float32Arrays are filled with 0s by default, we do not have to do that again. The cost of the `if` is negligible, compared to the potential performance gains.
Resolves: https://github.com/toji/gl-matrix/issues/301#issuecomment-394049372
> create() performance improvements

- package.json
For webpack and potentially other bundlers to be able to remove unused
code, it is necessary to declare that this package does not contain
side-effects when it is loaded.
For that, webpack introduced the "sideEffects" property in the
package.json file as described in
https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
This fixes #326
> Specify sideEffects=false in package.json to facilitate tree shaking

- spec/gl-matrix/vec2-spec.js
- spec/gl-matrix/vec3-spec.js
- spec/gl-matrix/vec4-spec.js
- src/vec2.js
- src/vec3.js
- src/vec4.js
Adding method to set all components of a vector to zero.
I often encounter this when working with cached vectors. Having a ``Vector.zero`` method is a more clear and probably faster way than calling ``Vector.set(out, 0, ..)``.
> Adding Vector.zero method

- src/mat4.js
Currently, using `mat4.getRotation` causes unexpected behaviors. I just took the implementation proposed by @kyasbal-1994 in #245
This leads to some tests breaking in quat2.
Maybe we should have separates functions, something like `getRotation` & `getUnscaledRotation`?
> Fixes #245 - getRotation scaled matrix

- src/mat2d.js
The order of the elements in the description comment in `mat2d` was incorrect as discussed in https://github.com/toji/gl-matrix/issues/360
> correct order in mat2d doc comment

- package.json
- utils/build.js
This change allows me to use the git repository directly as a dependency in my packages.json
.e.g 
```
"dependencies": { "gl-matrix": "git@github.com:stygianguest/gl-matrix.git#github_npm_dependency" }
```
might be useful to others as well
> GitHub npm dependency

- src/vec2.js
- src/vec3.js
No functionality changes, but some function inputs were renamed to match the usage in other classes, and the jsdoc updated to match. 
I lost an hour of debugging because it wasn't explicit in the docs that vec2/vec3 rotations were in radians, hopefully this prevents others from the same problem.
Also cleaned up some messy whitespace.
> Update docs to express angles are in radians

- src/vec2.js
As I understand it, because you're always calculating the inner angle (cosine θ),
the cosine var will never be greater than 1 or less than -1.
So
```js
if(cosine > 1.0) {
return 0;
}
else if(cosine < -1.0) {
return Math.PI;
} else {
return Math.acos(cosine);
}
```
will only ever reach the `else` clause.
The if statements could be updated with `>=` and `<=` to be reachable, 
and that makes sense, but performance is actually better without the conditional branches.
> Remove unreachable code from vec2.angle

- src/common.js
Typescript complained about unknown "Type". Judging from the code `Float32ArrayConstructor | ArrayConstructor` is appropriate.
> Set correct type for setMatrixArrayType

- package.json
- src/mat2.js
- src/mat2d.js
- src/mat3.js
- src/mat4.js
- src/quat.js
- src/quat2.js
- src/types.d.ts
- src/vec2.js
- src/vec3.js
- src/vec4.js
Add Readonly types for TypeScript.
Addresses #381, see that issue for justification and more details.
> Readonly types for TypeScript

- spec/gl-matrix/mat4-spec.js
- src/mat4.js
closes #401 . I settled on returning only the rotation quaternion.
I added some tests which are basically copies of the other `getX` functions, but let me know if some are spurious or more are required.
> add combined TRS decompose for mat4

- src/mat4.js
Putting this up as a pull request in case there's any feedback.
The upcoming WebGPU API uses Normalized Device Coordinates with a [0, 1] Z range, which differs from WebGL's [-1, 1] range. To get the best precision out of WebGPU pages will need to create perspective matrices a bit differently.
This change introduces the `mat4.perspectiveZO()`, which is identical in functionality to the previous `mat4.perspective()` method except it maps to the [0, -1] range. For consistency the previous method has been renamed to `mat4.perspectiveNO()` with an alias of `mat4.perspective()`. This could later allow users to configure the library to use one projection method or the other by default. Naming convention borrowed from the native [glm library](https://github.com/g-truc/glm) because I can't think …
> Add mat4.perspectiveZO, mat4.orthoZO for WebGPU

- spec/gl-matrix/quat-spec.js
- src/quat.js
The old method for quaternions equality returns false with flipped orientation (eg [0, 0, 0, 1] and [0, 0, 0, -1])
This pull request uses dot product instead, assuming quaternions are unit length
It is breaking change because old checks for equality when quaternions are not unit length won't work anymore
fixes #292
> fix!: use dot product to compute quaternions equality

- src/vec3.js
Math.sqrt() is heavy operation and can be used only once
> Optimize angle(v1, v2)

- spec/gl-matrix/vec2-spec.js
- spec/gl-matrix/vec3-spec.js
- spec/gl-matrix/vec4-spec.js
- src/vec2.js
- src/vec3.js
- src/vec4.js
I encountered unexpected behaviour when passing dynamic values to the `scale` parameter of `vec2.random`.
calling `random(vec, 0)` should return a vector of length `0`, not `1`.
> random should only return unit vector when scale is undefined

- src/common.js
- src/mat2.js
- src/mat2d.js
- src/mat3.js
- src/mat4.js
- src/quat2.js
- src/vec2.js
- src/vec3.js
- src/vec4.js
Fixes #446 
This PR replaces all instances of `Math.hypot` with `Math.sqrt`. It also removes the polyfill for hypot on really old browsers.
The reason is that `sqrt` is MUCH faster than `hypot` on all modern javascript engines. See #446 for some benchmarks.
While hypot is nicer to write, and is technically more accurate especially for very large and very small numbers, I think that the performance gains from switching to `sqrt` are worth it. Especially for a library with the goal:
> glMatrix is designed to perform vector and matrix operations stupidly fast!
Suggestions and feedback appreciated.
> Replace Math.hypot with Math.sqrt

- src/vec4.js
This pull request improves the performance of calculating `vec4.random`. See the benchmark [here](https://jsperf.app/yosado/3).
The old solution used a `while` loop to recalculate until `s1 <= 1` and `s2 <= 1`. This solution instead sets minimum and maximum values for `v2` and `v4` based on the values of `v1` and `v3`, respectively, using the standard formula `random * (max - min) + min`.
Let `v` be `v1` or `v3`. `a` is the random value in the range `[0,1]` that is used to calculate `v`. That is:
```ts
const a: number = Math.random();
const v: number = a * 2 - 1;
```
Let `w` be `v2` or `v4`. `b` is the random value in the range `[min,max]` that is used to calculate `w`. That is:
```ts
const b: number = Math.random() * (max - min) + min;
const w: number = b * 2 - 1;
```
Let `s` be `s1` or …
> Improve the Performance of `vec4.random`

- src/quat.js
The 'zyx' order was duplicated and 'xzy' was missing.
> Fix order param type in quat.fromEuler

- src/mat4.js
- src/vec4.js
This is to align parameters names to comments.
I'm using typedoc which complains about misalignment between docs comments and actual code.
I've fixed what it found (although the version I'm using is not from latest code).
Regardless, these fixes are correct.
It would be great if you could also release a new version after merging this.
Thanks!
> Align docs with parameters names

- src/mat4.js
In the doc comments for the `fromRotationTranslation...` functions, `quat4` is used as the type instead of `quat`. See https://github.com/toji/gl-matrix/blob/master/src/mat4.js#L1048
Also fixes typo mentioned in https://github.com/toji/gl-matrix/pull/419
> Fixes typos documentation comments in mat4.js

- spec/gl-matrix/mat2-spec.js
- spec/gl-matrix/mat2d-spec.js
- spec/gl-matrix/mat3-spec.js
- spec/gl-matrix/mat4-spec.js
- src/mat2.js
- src/mat2d.js
- src/mat3.js
- src/mat4.js
Fix return types of matrix `invert()` functions to allow `null`.
Fixing the return type is important because it lets us catch errors in TypeScript before we ship them to customers.
> Fix return types of matrix invert functions

- .gitignore
- package-lock.json
- package.json
The project had stopped building successfully, including when installing locally. This appears to be due to a change in one of `jsdoc`'s dependencies that was breaking the generation of TypeScript declaration files.
This also includes a `package-lock.json` file to avoid these kind of transitory dependency issues in the future :)
> Fix build errors by locking dependencies

- .github/workflows/push.yml
Following up on toji/gl-matrix#480, this adds a basic CI pipeline to the repository which runs tests on all branch pushes. A small change, but hopefully helpful :)
An example run is here, it should stick around for another week or two: https://github.com/hughsk-canva/gl-matrix/actions/runs/12759586150/job/35563603100
> Run tests on push using GitHub Actions

- utils/bundle-dts.js
Previously some namespace types were generated using the legacy `module` keyword from ten years ago. Now we emit the modern TS `namespace` keyword that has been the preferred keyword since TypeScript 1.5 in 2015.
Please review the resulting diff for the generated `dist/index.d.ts` file:  https://gist.github.com/robpalme/a320dc3f0cb50bcd14962bca46827dae/revisions
Note that the outer _Ambient Module Declaration_ intentionally remains untouched because it is not a namespace.  These are differentiated by using a quoted string rather than a bare identifier
`module "quoted" {`
vs
`module bare {`
---
Background:  This usage of the legacy keyword was found by [a TypeScript real-world test suite](https://github.com/microsoft/TypeScript/pull/61450#issuecomment-2744477736) that checks the …
> Fix generated namespace types in index.d.ts
